version: '3.8'

services:
    # php
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: php_filmlist
        environment:
            XDEBUG_SESSION: docker-server
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: "
            client_host=host.docker.internal
            start_with_request=yes
          "
        ports:
            - "9000:9000"
            - "8080:8080"
        volumes:
            - ./:/var/www
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_eporting.ini

    # mysql
    mysql:
        image: mysql:8
        platform: linux/amd64 # for MacOS with ARM. Delete for x86
        container_name: mysql_filmlist
        ports:
            - "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
